spring.application.name=minicrm
# Pfade zu deinen Message-Dateien (ohne .properties Endung angeben!)
spring.messages.basename=i18n/common_errors,i18n/common_messages,i18n/driver_errors,i18n/driver_messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
# Optional: Verhindert Fehler, wenn ein Key mal in einer Datei fehlt
spring.messages.fallback-to-system-locale=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


logging.level.org.springframework.security=DEBUG
spring.security.enabled=true
spring.security.user.name=marko
spring.security.user.password=marko
spring.security.user.roles=USER
logging.level.root=INFO
#logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web=ERROR


## APP CONFIG
jwt.secret=my1super1secret1key1with132chars!

spring.datasource.url=jdbc:postgresql://localhost:5432/minicrm
spring.datasource.username=marko
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

security.token.access.expiration-minutes=30
security.token.refresh.expiration-minutes=10080
